---
title: "hw2.0-Gapminder and dplyr"
author: "Xuan Lin"
date: '2019-09-21'
output: 
  html_document:
    keep_md: true
    toc: true
---

## Setup
```{r echo=FALSE, warning=FALSE}
library(gapminder)
library(tidyverse)
```

## _Exercise 1_ Basic dplyr
### __1.1__
```{r echo=FALSE}
filter(gapminder, year== 1972 | year== 1977, country== "China" | country=="Canada" | country=="Japan") %>% 
knitr::kable()
```

### __1.2__
```{r echo=FALSE}
filter(gapminder, year== 1972 | year== 1977, country== "China" | country=="Canada" | country=="Japan") %>% 
  select(country, gdpPercap) %>% 
  knitr::kable()
```

### __1.3__
```{r echo=FALSE}
gapminder %>% 
  group_by(country) %>% 
  mutate(increaseInlifeExp = c(0, diff(lifeExp, 1))) %>% 
  filter(increaseInlifeExp < 0) %>% 
  DT::datatable()
```


### __1.4__
```{r echo=FALSE}
gapminder %>% 
  group_by(country) %>% 
  filter(gdpPercap == max(gdpPercap)) %>% 
  DT::datatable()
```

### __1.5__


```{r echo=FALSE}
gapminder %>%
  filter(country == "Canada") %>% 
  ggplot(aes(lifeExp, gdpPercap)) +
  geom_point() +
  scale_y_log10("GDP per capita", labels = scales::dollar_format()) +
  xlab("Life Expectancy")
```

## _Exercise 2_ Explore individual variables with dplyr
__Minimum and maximum life expetancy each year:__

```{r echo=FALSE}
gapminder %>%
  group_by(year) %>% 
  filter(lifeExp == max(lifeExp) | lifeExp == min(lifeExp)) %>% 
  select(year, lifeExp) %>% 
  arrange(year, lifeExp) %>% 
  knitr::kable()
```

__Boxplot of life expectancy each year:__

```{r echo=FALSE}
gapminder %>%
  ggplot(aes(year, lifeExp)) +
  geom_boxplot(aes(group = year)) +
  xlab("Year") +
  ylab("Life Expectancy")
```


## _Exercise 3_ Explore various plot types
### A scatterplot of two quantitative variables

### One other plot besides a scatterplot

## _Recycling_
The given code retures the data for Rwanda and Afghanistan.
```{r}
filter(gapminder, country == c("Rwanda", "Afghanistan"))
```


